version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Linting
          command : |
            . venv/bin/activate
            flake8
      - run :
          name : Test with pytest
          command : |
            . venv/bin/activate
            pytest

  deploy:
    docker:
      -image: cimg/python:3.10.2
    machine:
      true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push to DockerHub
          command: |
            docker build -t $DOCKER_USER_ID/$IMAGE_NAME:latest .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_USER_ID" --password-stdin
            docker push  $DOCKER_USER_ID/$IMAGE_NAME:latest

workflows:
    version: 2
    build-master:
      jobs:
        - build
        - deploy:
            requires:
              - build
