version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Linting
          command : |
            . env/bin/activate
            flake8
      - run :
          name : Test with pytest
          command : |
            . env/bin/activate
            pytest

workflows:
    version: 2
    build-master:
      jobs:
        - build
