# Generated by Django 3.0 on 2023-01-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20230128_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
